### ISSUE TITLE
Modify automation pipeline such that can be used with keys per subgroup

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-app-build-trigger#4]

**Comment by mcduffie** [comment]
Each subproject should be related to a venue or customer

**Comment by GodwinShen** [comment]
@mcduffie I see that this is still in progress, can we get an update on this ticket?

**Comment by edwinsarkissian** [comment]
I have just started to work this task. Edwin

**Comment by mcduffie** [comment]
Can now clone to different subgroups per authentication. Will add new task for associating user with project groups.
