### ISSUE TITLE
Automate creation of MCP subgroups

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-app-build-trigger#9]

**Comment by mcduffie** [comment]
@edwinsarkissian Still investigating remotely creating sub groups

**Comment by GodwinShen** [comment]
@mcduffie and @edwinsarkissian ping for status.

**Comment by edwinsarkissian** [comment]
This may not be doable. I have spent time looking for a way of enabling auto subgroup creation, but I have not been able to find a way.  This was proposed in https://gitlab.com/gitlab-org/gitlab-foss/-/issues/31831 issue, but I don't believe it has been implemented.  I will spend more time looking into this next week.

**Comment by edwinsarkissian** [comment]
I spent plenty of time and could not find anything online suggesting that it would be possible to automatically create gitlab subgroup upon git push. I also looked at "glab" and did not find anything for automatic subgroup creation. About seven years ago some proposed adding auto subgroup creation feature to gitlab, please see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/31831. Four years later a person raised this issue again and asked for a way to auto create gitlab subgroup, but he got no response, please see https://forum.gitlab.com/t/create-repository-and-subgroups-by-cli-and-gitlab-14/55699. Even if glab had the interface for auto creating a subgroup, I would not recommend using it. The tool appears to be not reliable, please see https://www.reddit.com/r/gitlab/comments/11pgelz/gitlab_cli_tool_almost_completely_useless_buggy/.  Upon online search, I find only a few sites related to auto subgroup creation.
We should close this issue, and come back to it in the future if need be.

**Comment by mcduffie** [comment]
Won't implement due to difficulties doing so automatically.
